# Generated by Django 5.0.14 on 2026-04-16 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_main', models.CharField(blank=True, help_text='Пусто = значение из settings.AI_MODEL_MAIN', max_length=128)),
                ('model_light', models.CharField(blank=True, max_length=128)),
                ('model_fallback', models.CharField(blank=True, max_length=128)),
                ('enable_discovery', models.BooleanField(default=True)),
                ('enable_book_chat', models.BooleanField(default=True)),
                ('enable_recommendations', models.BooleanField(default=True)),
                ('enable_ai_search', models.BooleanField(default=True)),
                ('enable_tag', models.BooleanField(default=True)),
                ('enable_mood', models.BooleanField(default=True)),
                ('enable_quotes', models.BooleanField(default=True)),
                ('enable_sentiment', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI configuration',
            },
        ),
        migrations.CreateModel(
            name='AIAdminChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_admin_chat', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AIAdminChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'user'), ('assistant', 'assistant')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_admin.aiadminchat')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('feature', models.CharField(choices=[('discovery', 'Discovery chat'), ('book_chat', 'Book chat'), ('recommendations', 'Recommendations'), ('ai_search', 'AI search'), ('tag', 'Tag extraction'), ('mood', 'Mood classification'), ('quotes', 'Smart quotes'), ('sentiment', 'List sentiment'), ('admin_chat', 'Admin chat'), ('other', 'Other')], db_index=True, default='other', max_length=32)),
                ('tier', models.CharField(choices=[('main', 'main'), ('light', 'light')], default='main', max_length=10)),
                ('model', models.CharField(blank=True, max_length=128)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('latency_ms', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('error', 'Error'), ('rate_limit', 'Rate limit')], db_index=True, default='ok', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('request_preview', models.TextField(blank=True)),
                ('response_preview', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'feature'], name='ai_admin_ai_created_18b8e5_idx'), models.Index(fields=['-created_at', 'status'], name='ai_admin_ai_created_08438a_idx')],
            },
        ),
    ]
