# Generated by Django 5.0.14 on 2026-04-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_admin', '0003_remove_admin_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconfig',
            name='enable_book_search',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aiconfig',
            name='enable_book_style',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aiconfig',
            name='enable_book_themes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aiconfig',
            name='enable_chapter_summary',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='aiusagelog',
            name='feature',
            field=models.CharField(choices=[('discovery', 'Discovery chat'), ('book_chat', 'Book chat'), ('recommendations', 'Recommendations'), ('ai_search', 'AI search'), ('tag', 'Tag extraction'), ('mood', 'Mood classification'), ('quotes', 'Smart quotes'), ('sentiment', 'List sentiment'), ('chapter_summary', 'Chapter summary'), ('book_themes', 'Book themes'), ('book_search', 'In-book semantic search'), ('book_style', 'Book style profile'), ('other', 'Other')], db_index=True, default='other', max_length=32),
        ),
    ]
