# Generated by Django 5.0.14 on 2026-04-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_admin', '0004_aiconfig_enable_book_search_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconfig',
            name='dry_run_mode',
            field=models.BooleanField(default=False, help_text='Сухой режим: LLM-вызовы логируются, но реального запроса к API не делают. Возвращается фейковый ответ. Включите перед массовыми импортами, чтобы не палить токены.'),
        ),
        migrations.AlterField(
            model_name='aiusagelog',
            name='status',
            field=models.CharField(choices=[('ok', 'OK'), ('error', 'Error'), ('rate_limit', 'Rate limit'), ('dry_run', 'Dry run (no API call)')], db_index=True, default='ok', max_length=16),
        ),
    ]
