# Generated by Django 5.0.14 on 2026-04-27 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curated', '0004_collectioncomment_parent_collectioncommentvote'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='collectioncomment',
            new_name='curated_col_collect_40abb1_idx',
            old_name='curated_col_collect_f521c3_idx',
        ),
    ]
