# Generated by Django 5.0.14 on 2026-04-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
