# Generated by Django 5.0.14 on 2026-04-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userblockhistory'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userblockhistory',
            new_name='users_userb_user_id_89c6e6_idx',
            old_name='users_userb_user_id_bd61db_idx',
        ),
        migrations.RenameIndex(
            model_name='userblockhistory',
            new_name='users_userb_blocked_ad8626_idx',
            old_name='users_userb_blocked_76826b_idx',
        ),
        migrations.AlterField(
            model_name='userblockhistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
