from django.urls import path
from . import views, author_views

urlpatterns = [
    path("",                                        views.catalog,                    name="catalog"),
    path("<int:pk>/",                               views.book_detail,                name="book_detail"),
    path("toggle-list/",                            views.toggle_list,                name="toggle_list"),
    path("<int:pk>/request-price/",                 views.request_price,              name="request_price"),
    path("<int:pk>/price-status/",                  views.price_status,               name="price_status"),
    path("<int:pk>/price-chart/",                   views.price_chart_data,           name="price_chart_data"),
    path("<int:pk>/price-alert/save/",              views.price_alert_save,           name="price_alert_save"),
    path("<int:pk>/price-alert/delete/",            views.price_alert_delete,         name="price_alert_delete"),
    path("<int:book_id>/store-link/save/",          views.store_link_save,            name="store_link_save"),
    path("<int:book_id>/store-link/<int:store_id>/delete/",
                                                    views.store_link_delete,          name="store_link_delete"),
    path("<int:pk>/progress/",                      views.reading_progress_save,      name="reading_progress_save"),
    # Полный текст книги (EPUB/FB2) + читалка
    path("<int:pk>/text/upload/",                   views.book_text_upload,           name="book_text_upload"),
    path("<int:pk>/text/delete/",                   views.book_text_delete,           name="book_text_delete"),
    path("<int:pk>/read/",                          views.book_read,                  name="book_read"),
    path("<int:pk>/read/<int:chapter_order>/",      views.book_read,                  name="book_read_chapter"),
    path("<int:pk>/read/progress/",                 views.book_read_progress,         name="book_read_progress"),
    path("<int:pk>/quotes/",                        views.quotes_partial,             name="quotes_partial"),
    path("<int:pk>/quotes/add/",                    views.quote_add,                  name="quote_add"),
    path("<int:pk>/quotes/<int:quote_pk>/delete/",  views.quote_delete,               name="quote_delete"),
    path("<int:pk>/notes/add/",                     views.note_add,                   name="note_add"),
    path("<int:pk>/notes/list/",                    views.note_list_for_book,         name="note_list_for_book"),
    path("notes/<int:note_id>/delete/",             views.note_delete,                name="note_delete"),
    path("admin/delete/<int:pk>/",                  views.admin_delete_book,          name="admin_delete_book"),
    path("admin/partial/",                          views.admin_books_partial,        name="admin_books_partial"),
    # AI-фичи полного текста (staff only, требуют загруженного BookText)
    path("<int:pk>/ai/summaries/",                  views.book_ai_summaries,          name="book_ai_summaries"),
    path("<int:pk>/ai/quotes-extract/",             views.book_ai_quotes_extract,     name="book_ai_quotes_extract"),
    path("<int:pk>/ai/themes/",                     views.book_ai_themes,             name="book_ai_themes"),
    path("<int:pk>/ai/style/",                      views.book_ai_style,              name="book_ai_style"),
    # Семантический поиск по главам (читалка)
    path("<int:pk>/chapter-search/",                views.book_chapter_search,        name="book_chapter_search"),
    path("add/",                                    views.book_add,                   name="book_add"),
    path("isbn-lookup/",                            views.isbn_lookup,                name="isbn_lookup"),
    path("add/author/",                             views.author_create_inline,       name="author_create_inline"),
    path("add/genre/",                              views.genre_create_inline,        name="genre_create_inline"),
    path("add/publisher/",                          views.publisher_create_inline,    name="publisher_create_inline"),
    path("add/series/",                             views.series_create_inline,       name="series_create_inline"),
    path("<int:pk>/edit/",                          views.book_edit,                  name="book_edit"),
    path("<int:pk>/mood/<int:mood_id>/vote/",       views.vote_mood,                  name="vote_mood"),
    path("series/<int:pk>/",                          views.series_detail,              name="series_detail"),

    # Группы изданий
    path("<int:pk>/edition-data/",                    views.edition_data,               name="edition_data"),
    path("editions/",                                 views.editions_list,              name="editions_list"),
    path("editions/create/",                          views.edition_create,             name="edition_create"),
    path("editions/<int:pk>/edit/",                   views.edition_edit,               name="edition_edit"),
    path("editions/<int:pk>/add-book/",               views.edition_add_book,           name="edition_add_book"),
    path("editions/<int:pk>/remove-book/<int:book_id>/", views.edition_remove_book,    name="edition_remove_book"),
    path("editions/<int:pk>/delete/",                 views.edition_delete,             name="edition_delete"),
    path("editions/search-books/",                    views.edition_search_books,       name="edition_search_books"),
    path("authors/<int:pk>/",                       author_views.author_detail,       name="author_detail"),
    path("authors/<int:pk>/edit/",                  author_views.author_edit,         name="author_edit"),
    path("authors/<int:pk>/subscribe/",             author_views.toggle_author_subscription, name="author_subscribe"),
    path("publishers/<int:pk>/",                    author_views.publisher_detail,    name="publisher_detail"),
    path("publishers/<int:pk>/edit/",               author_views.publisher_edit,      name="publisher_edit"),
]
