# Generated by Django 5.0.14 on 2026-04-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_user_notify_action'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='moderationlog',
            new_name='analytics_m_created_868d2a_idx',
            old_name='analytics_m_created_ac_idx',
        ),
        migrations.RenameIndex(
            model_name='storeclick',
            new_name='analytics_s_created_4d9066_idx',
            old_name='analytics_s_created_st_idx',
        ),
        migrations.RenameIndex(
            model_name='storeclick',
            new_name='analytics_s_created_bec259_idx',
            old_name='analytics_s_created_bk_idx',
        ),
        migrations.AlterField(
            model_name='moderationlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='storeclick',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
