# Generated by Django 5.0.14 on 2026-04-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_quote_ai_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='series_order',
            field=models.PositiveIntegerField(blank=True, help_text='Порядковый номер книги в серии', null=True),
        ),
    ]
