# Generated by Django 5.0.14 on 2026-04-15 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_series_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Каноническое название произведения (для админа)', max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='edition_group',
            field=models.ForeignKey(blank=True, help_text='Группа изданий этой книги (разные издатели)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.bookedition'),
        ),
    ]
