# Generated by Django 5.0.14 on 2026-04-23 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_bookedition_book_edition_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, help_text='Порядковый номер главы (0-based).')),
                ('title', models.CharField(blank=True, max_length=300)),
                ('html', models.TextField(help_text='Очищенный HTML главы для рендера в читалке.')),
                ('text', models.TextField(help_text='Plain text главы для AI.')),
                ('word_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='readingprogress',
            name='scroll_offset',
            field=models.FloatField(default=0.0, help_text='0.0-1.0 — относительная позиция скролла внутри текущей главы'),
        ),
        migrations.AddField(
            model_name='readingprogress',
            name='current_chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='books.bookchapter'),
        ),
        migrations.CreateModel(
            name='BookText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.FileField(upload_to='book_texts/')),
                ('source_format', models.CharField(choices=[('epub', 'EPUB'), ('fb2', 'FB2')], max_length=10)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('char_count', models.PositiveIntegerField(default=0)),
                ('extract_status', models.CharField(choices=[('pending', 'В обработке'), ('ok', 'Извлечено'), ('error', 'Ошибка парсинга')], default='pending', max_length=16)),
                ('extract_error', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='text', to='books.book')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Полный текст книги',
            },
        ),
        migrations.AddField(
            model_name='bookchapter',
            name='book_text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='books.booktext'),
        ),
        migrations.AddIndex(
            model_name='bookchapter',
            index=models.Index(fields=['book_text', 'order'], name='books_bookc_book_te_8d6cea_idx'),
        ),
        migrations.AddConstraint(
            model_name='bookchapter',
            constraint=models.UniqueConstraint(fields=('book_text', 'order'), name='bookchapter_order_unique'),
        ),
    ]
