# Generated by Django 5.0.14 on 2026-04-23 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_readingprogress_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ai_style_profile',
            field=models.JSONField(blank=True, default=dict, help_text='Профиль стиля (тон, темп, POV...) из первых глав — для spoiler-safe рекомендаций.'),
        ),
        migrations.AddField(
            model_name='book',
            name='ai_themes',
            field=models.JSONField(blank=True, default=list, help_text='Список тем/мотивов книги, извлечённых AI из полного текста.'),
        ),
        migrations.AddField(
            model_name='bookchapter',
            name='summary',
            field=models.TextField(blank=True, help_text='Краткое AI-содержание главы (1-2 предложения, без спойлеров финала).'),
        ),
        migrations.AddField(
            model_name='bookchapter',
            name='summary_status',
            field=models.CharField(choices=[('pending', 'В очереди'), ('ok', 'Готово'), ('error', 'Ошибка')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='quote',
            name='chapter',
            field=models.ForeignKey(blank=True, help_text='Глава, из которой взята цитата (если применимо).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='books.bookchapter'),
        ),
    ]
