# Repair migration for deployments where chat.0004 was applied before
# ClubBookThread was moved into its own table.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_book_thread_room"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS chat_clubbookthread (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                club_book_id bigint NOT NULL UNIQUE
                    REFERENCES clubs_clubbook(id) DEFERRABLE INITIALLY DEFERRED,
                room_id bigint NOT NULL UNIQUE
                    REFERENCES chat_chatroom(id) DEFERRABLE INITIALLY DEFERRED
            );
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
