# Generated by Django 5.0.4 on 2026-04-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chat', '0002_discoverychat'),
    ]

    operations = [
        migrations.AddField(
            model_name='discoverychatmessage',
            name='books_meta',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
