# Generated by Django 5.0.14 on 2026-04-27 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ticket',
            new_name='tickets_tic_kind_e71227_idx',
            old_name='tickets_tic_kind_8b0e1c_idx',
        ),
        migrations.RenameIndex(
            model_name='ticket',
            new_name='tickets_tic_user_id_64e790_idx',
            old_name='tickets_tic_user_id_4b6e8b_idx',
        ),
    ]
